USE [master]
GO
/****** Object:  Database [AssetManagement]    Script Date: 01-10-2019 11:03:23 ******/
CREATE DATABASE [AssetManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AssetManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESSNEW\MSSQL\DATA\AssetManagement.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AssetManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESSNEW\MSSQL\DATA\AssetManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AssetManagement] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AssetManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AssetManagement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AssetManagement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AssetManagement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AssetManagement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AssetManagement] SET ARITHABORT OFF 
GO
ALTER DATABASE [AssetManagement] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AssetManagement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AssetManagement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AssetManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AssetManagement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AssetManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AssetManagement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AssetManagement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AssetManagement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AssetManagement] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AssetManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AssetManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AssetManagement] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AssetManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AssetManagement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AssetManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AssetManagement] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AssetManagement] SET RECOVERY FULL 
GO
ALTER DATABASE [AssetManagement] SET  MULTI_USER 
GO
ALTER DATABASE [AssetManagement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AssetManagement] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AssetManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AssetManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AssetManagement] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AssetManagement] SET QUERY_STORE = OFF
GO
USE [AssetManagement]
GO
/****** Object:  User [ams]    Script Date: 01-10-2019 11:03:23 ******/
CREATE USER [ams] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO