//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetManagementEntities : DbContext
    {
        public AssetManagementEntities()
            : base("name=AssetManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetCategory> AssetCategories { get; set; }
        public virtual DbSet<AssetLocation> AssetLocations { get; set; }
        public virtual DbSet<AssetPaymentMode> AssetPaymentModes { get; set; }
        public virtual DbSet<AssetRequest> AssetRequests { get; set; }
        public virtual DbSet<AssetRequestSpecification> AssetRequestSpecifications { get; set; }
        public virtual DbSet<AssetSpecification> AssetSpecifications { get; set; }
        public virtual DbSet<AssetStatu> AssetStatus { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AssetTypeSpecification> AssetTypeSpecifications { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<AssetDocument> AssetDocuments { get; set; }
        public virtual DbSet<AssetQuoteApproval> AssetQuoteApprovals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AssetHistory> AssetHistories { get; set; }
        public virtual DbSet<UserRoleMap> UserRoleMaps { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<AssetRequestPayment> AssetRequestPayments { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetVendor> AssetVendors { get; set; }
        public virtual DbSet<AssetTypeOtherSpecification> AssetTypeOtherSpecifications { get; set; }
        public virtual DbSet<AssetAllocation> AssetAllocations { get; set; }
        public virtual DbSet<AssetQuotation> AssetQuotations { get; set; }
        public virtual DbSet<Vw_PendingAssets> Vw_PendingAssets { get; set; }
        public virtual DbSet<Vw_UnallocatedAssets> Vw_UnallocatedAssets { get; set; }
        public virtual DbSet<AssetTypeAddOn> AssetTypeAddOns { get; set; }
        public virtual DbSet<Vw_Assets> Vw_Assets { get; set; }
    }
}
