//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetAllocation
    {
        public long AssetAllocationId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public System.DateTime AssetAllocatedOn { get; set; }
        public Nullable<System.DateTime> AssetCanceledOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string AllocationComments { get; set; }
        public string CancellationComments { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual AssetLocation AssetLocation { get; set; }
    }
}
