//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRequestPayment
    {
        public long Id { get; set; }
        public Nullable<long> AssetRequestId { get; set; }
        public Nullable<long> PaymentModeId { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<int> Tax { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string CreditCardNo { get; set; }
        public string CreditCardOwner { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeBankName { get; set; }
        public string ChequeBranch { get; set; }
        public string DC_TransactionIdentifier { get; set; }
        public string DC_Transferer { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string Payee { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual AssetPaymentMode AssetPaymentMode { get; set; }
        public virtual AssetRequest AssetRequest { get; set; }
    }
}
