//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetQuotation()
        {
            this.AssetRequests = new HashSet<AssetRequest>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AssetRequestId { get; set; }
        public Nullable<long> AssetVendorId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Comments { get; set; }
        public string Documents { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual AssetVendor AssetVendor { get; set; }
        public virtual AssetRequest AssetRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetRequest> AssetRequests { get; set; }
    }
}
