//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetRequest()
        {
            this.AssetRequestSpecifications = new HashSet<AssetRequestSpecification>();
            this.AssetHistories = new HashSet<AssetHistory>();
            this.AssetRequestPayments = new HashSet<AssetRequestPayment>();
            this.Assets = new HashSet<Asset>();
            this.AssetTypeOtherSpecifications = new HashSet<AssetTypeOtherSpecification>();
            this.AssetTypeOtherSpecifications1 = new HashSet<AssetTypeOtherSpecification>();
            this.AssetTypeOtherSpecifications2 = new HashSet<AssetTypeOtherSpecification>();
            this.AssetTypeOtherSpecifications3 = new HashSet<AssetTypeOtherSpecification>();
            this.AssetQuotations = new HashSet<AssetQuotation>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AssetTypeId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> AssetQuotationId { get; set; }
        public string PONumber { get; set; }
        public string ARNumber { get; set; }
        public Nullable<long> AssetStatusId { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual AssetLocation AssetLocation { get; set; }
        public virtual AssetType AssetType { get; set; }
        public virtual AssetStatu AssetStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetRequestSpecification> AssetRequestSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetHistory> AssetHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetRequestPayment> AssetRequestPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTypeOtherSpecification> AssetTypeOtherSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTypeOtherSpecification> AssetTypeOtherSpecifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTypeOtherSpecification> AssetTypeOtherSpecifications2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTypeOtherSpecification> AssetTypeOtherSpecifications3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetQuotation> AssetQuotations { get; set; }
        public virtual AssetQuotation AssetQuotation { get; set; }
    }
}
