//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTypeOtherSpecification
    {
        public long Id { get; set; }
        public Nullable<long> AssetRequestId { get; set; }
        public string OtherSpecification { get; set; }
    
        public virtual AssetRequest AssetRequest { get; set; }
        public virtual AssetRequest AssetRequest1 { get; set; }
        public virtual AssetRequest AssetRequest2 { get; set; }
        public virtual AssetRequest AssetRequest3 { get; set; }
    }
}
