//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRequestSpecification
    {
        public long Id { get; set; }
        public Nullable<long> AssetRequestId { get; set; }
        public Nullable<long> AssetTypeSpecId { get; set; }
        public string AssetTypeSpecValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual AssetRequest AssetRequest { get; set; }
        public virtual AssetTypeSpecification AssetTypeSpecification { get; set; }
    }
}
