//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Users = new HashSet<User>();
            this.AssetHistories = new HashSet<AssetHistory>();
            this.UserRoleMaps = new HashSet<UserRoleMap>();
            this.AssetAllocations = new HashSet<AssetAllocation>();
        }
    
        public long UserId { get; set; }
        public string EmployeeId { get; set; }
        public string LoginId { get; set; }
        public Nullable<long> OfficeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<long> ReportingToId { get; set; }
        public Nullable<long> OfficeHolidayId { get; set; }
        public Nullable<long> EmployeeRoleId { get; set; }
        public Nullable<bool> IsHandleMembers { get; set; }
        public Nullable<bool> IsInProbationaryPeriod { get; set; }
        public Nullable<bool> CanAvailYearlyLeave { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<long> CardID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public string CorpId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetHistory> AssetHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleMap> UserRoleMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetAllocation> AssetAllocations { get; set; }
    }
}
