//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMap
    {
        public long Id { get; set; }
        public Nullable<long> EmployeeUserId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
