//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Assets
    {
        public long AssetId { get; set; }
        public string AssetTagNumber { get; set; }
        public Nullable<long> AssetRequestId { get; set; }
        public string AssetIdentifier { get; set; }
        public Nullable<long> Price { get; set; }
        public System.DateTime PurchaseOrderOn { get; set; }
        public string ServiceTagNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> AssetTypeId { get; set; }
    }
}
