//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_PendingAssets
    {
        public System.DateTime CreatedOn { get; set; }
        public string PONumber { get; set; }
        public string Name { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string VendorName { get; set; }
        public string MobileNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string LocationName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long Id { get; set; }
        public string Email { get; set; }
        public string LandLineNo { get; set; }
        public int CreatedBy { get; set; }
        public long UserId { get; set; }
        public string RaisedBy { get; set; }
    }
}
