//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UnallocatedAssets
    {
        public string Name { get; set; }
        public string RequestedFor { get; set; }
        public string RequestedBy { get; set; }
        public string AssetTagNumber { get; set; }
        public string LocationName { get; set; }
    }
}
